### ISSUE TITLE
Application crashes

### ISSUE THREAD

**Issue by peileppe** [sirpercival/PercivalsQuest#11]
Please enter your player name> brenan
Welcome, brenan! You don't have a character saved...
Time to make a new character! It'll be saved under this player name.
It's time to generate a character! At any of the prompts below, enter
'random' (no quotes) to use a random choice.
Available races: drow, dwarf, elf, gnome, halfling, human, orc
Race> gnome
Available classes: barbarian, bard, cleric, druid, fighter, monk, paladin, psion, ranger, rogue, samurai, wizard
Class> wizard
Available feats: ImprovedInitiative, IronWill, LightningReflexes, PowerAttack, Prodigy, StoutDefense, Toughness
Feat> Powerattack
Traceback (most recent call last):
  File "percivalsquest.py", line 214, in <module>
    main()
  File "percivalsquest.py", line 198, in main
    rpg_instance = generate(rpg_instance)
  File "percivalsquest.py", line 161, in generate
    rpg.character.chargen(rpg.player_name)
  File "/home/p/Documents/python/games/PercivalsQuest/pq_characters.py", line 72, in chargen
    self.chargenerate(race, clas, feats, player)
  File "/home/p/Documents/python/games/PercivalsQuest/pq_characters.py", line 76, in chargenerate
    self.name = [web_namegen(5, 12, 2).replace('\n', ' '), player]
  File "/home/p/Documents/python/games/PercivalsQuest/pq_namegen.py", line 102, in web_namegen
    return proxy.names(minsyl, maxsyl, n)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1233, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1587, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1273, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1321, in single_request
    response.msg,
xmlrpclib.ProtocolError: <ProtocolError for dicelog.com/yaf/rpc: 301 Moved Permanently>

**Comment by peileppe** [comment]
I fixed the issue -> https://github.com/peileppe/PercivalsQuest
